
package crypto;

import java.awt.Desktop;
import java.awt.TextField;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;

import javax.swing.JFileChooser;

//import crypto.des.DES_Encryptor;
/**
 *
 * @author abdelkarim
 */
public class GUI extends javax.swing.JFrame {

    /** Creates new form GUI */
    public GUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel1 = new javax.swing.JPanel();
        cipher_path = new java.awt.TextField();
        plain_path = new java.awt.TextField();
        key_path = new java.awt.TextField();
        attack_path = new java.awt.TextField();
        Browse_plainText = new java.awt.Button();
        Browse_cipher = new java.awt.Button();
        Browse_key = new java.awt.Button();
        Browse_attack = new java.awt.Button();
        open_plainText = new java.awt.Button();
        open_cipherText = new java.awt.Button();
        open_key = new java.awt.Button();
        open_attack = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        encrypt_button_OneTimePad = new java.awt.Button();
        Decrypt_button_OneTimePad = new java.awt.Button();
        attack_button_OneTimePad = new java.awt.Button();
        jPanel3 = new javax.swing.JPanel();
        encrypt_button_Vigenere = new java.awt.Button();
        Decrypt_button_Vigenere = new java.awt.Button();
        attack_button_Vigenere = new java.awt.Button();
        jPanel4 = new javax.swing.JPanel();
        encrypt_button_DES = new java.awt.Button();
        Decrypt_button_DES = new java.awt.Button();
        attack_button_DES = new java.awt.Button();
        jPanel5 = new javax.swing.JPanel();
        encrypt_button_Hill = new java.awt.Button();
        Decrypt_button_Hill = new java.awt.Button();
        attack_button_Hill = new java.awt.Button();
        jPanel6 = new javax.swing.JPanel();
        encrypt_button_RailFence = new java.awt.Button();
        Decrypt_button_RailFence = new java.awt.Button();
        attack_button_RailFence = new java.awt.Button();
        jPanel7 = new javax.swing.JPanel();
        encrypt_button_RSA = new java.awt.Button();
        Decrypt_button_RSA = new java.awt.Button();
        attack_button_RSA = new java.awt.Button();
        jPanel8 = new javax.swing.JPanel();
        encrypt_button_AES = new java.awt.Button();
        Decrypt_button_AES = new java.awt.Button();
        attack_button_AES = new java.awt.Button();
        jPanel9 = new javax.swing.JPanel();
        encrypt_button_RowTranspostion = new java.awt.Button();
        Decrypt_button_RowTranspostion = new java.awt.Button();
        attack_button_RowTranspostion = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cryptography");
        setBackground(new java.awt.Color(0, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Bitstream Charter", 1, 14)); // NOI18N
        setForeground(new java.awt.Color(255, 51, 204));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "I/O table", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 0, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 51, 204));

        cipher_path.setBackground(new java.awt.Color(0, 102, 102));
        cipher_path.setForeground(new java.awt.Color(255, 51, 204));
        cipher_path.setText("cipher_text.txt");

        plain_path.setBackground(new java.awt.Color(0, 102, 102));
        plain_path.setForeground(new java.awt.Color(255, 51, 204));
        plain_path.setText("plain_text.txt");

        key_path.setBackground(new java.awt.Color(0, 102, 102));
        key_path.setForeground(new java.awt.Color(255, 51, 204));
        key_path.setText("key.txt");

        attack_path.setBackground(new java.awt.Color(0, 102, 102));
        attack_path.setForeground(new java.awt.Color(255, 51, 204));
        attack_path.setText("attack.txt");

        Browse_plainText.setActionCommand("Browse");
        Browse_plainText.setBackground(new java.awt.Color(0, 102, 102));
        Browse_plainText.setForeground(new java.awt.Color(255, 0, 204));
        Browse_plainText.setLabel("Browse");
        Browse_plainText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Browse_plainTextActionPerformed(evt);
            }
        });

        Browse_cipher.setBackground(new java.awt.Color(0, 102, 102));
        Browse_cipher.setForeground(new java.awt.Color(255, 0, 204));
        Browse_cipher.setLabel("Browse");
        Browse_cipher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Browse_cipherActionPerformed(evt);
            }
        });

        Browse_key.setBackground(new java.awt.Color(0, 102, 102));
        Browse_key.setForeground(new java.awt.Color(255, 0, 204));
        Browse_key.setLabel("Browse");
        Browse_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Browse_keyActionPerformed(evt);
            }
        });

        Browse_attack.setBackground(new java.awt.Color(0, 102, 102));
        Browse_attack.setForeground(new java.awt.Color(255, 0, 204));
        Browse_attack.setLabel("Browse");
        Browse_attack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Browse_attackActionPerformed(evt);
            }
        });

        open_plainText.setActionCommand("Open");
        open_plainText.setBackground(new java.awt.Color(0, 102, 102));
        open_plainText.setForeground(new java.awt.Color(255, 0, 204));
        open_plainText.setLabel("Open");
        open_plainText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_plainTextActionPerformed(evt);
            }
        });

        open_cipherText.setActionCommand("Open");
        open_cipherText.setBackground(new java.awt.Color(0, 102, 102));
        open_cipherText.setForeground(new java.awt.Color(255, 0, 204));
        open_cipherText.setLabel("Open");
        open_cipherText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_cipherTextActionPerformed(evt);
            }
        });

        open_key.setActionCommand("Open");
        open_key.setBackground(new java.awt.Color(0, 102, 102));
        open_key.setForeground(new java.awt.Color(255, 0, 204));
        open_key.setLabel("Open");
        open_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_keyActionPerformed(evt);
            }
        });

        open_attack.setActionCommand("Open");
        open_attack.setBackground(new java.awt.Color(0, 102, 102));
        open_attack.setForeground(new java.awt.Color(255, 0, 204));
        open_attack.setLabel("Open");
        open_attack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_attackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cipher_path, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(key_path, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attack_path, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(plain_path, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(open_plainText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(open_cipherText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(open_key, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(open_attack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Browse_key, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(Browse_cipher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Browse_plainText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Browse_attack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(plain_path, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Browse_plainText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(open_plainText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cipher_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(open_cipherText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Browse_cipher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(open_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Browse_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(key_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(open_attack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Browse_attack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(attack_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Browse_plainText.getAccessibleContext().setAccessibleName("");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "One Time Pad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 51, 204))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 51, 204));

        encrypt_button_OneTimePad.setActionCommand("Encrypt");
        encrypt_button_OneTimePad.setBackground(new java.awt.Color(0, 102, 102));
        encrypt_button_OneTimePad.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        encrypt_button_OneTimePad.setForeground(new java.awt.Color(255, 0, 204));
        encrypt_button_OneTimePad.setLabel("Encrypt");
        encrypt_button_OneTimePad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encrypt_button_OneTimePadActionPerformed(evt);
            }
        });

        Decrypt_button_OneTimePad.setActionCommand("Decrypt");
        Decrypt_button_OneTimePad.setBackground(new java.awt.Color(0, 102, 102));
        Decrypt_button_OneTimePad.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        Decrypt_button_OneTimePad.setForeground(new java.awt.Color(255, 0, 204));
        Decrypt_button_OneTimePad.setLabel("Decrypt");
        Decrypt_button_OneTimePad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decrypt_button_OneTimePadActionPerformed(evt);
            }
        });

        attack_button_OneTimePad.setActionCommand("Attack");
        attack_button_OneTimePad.setBackground(new java.awt.Color(0, 102, 102));
        attack_button_OneTimePad.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        attack_button_OneTimePad.setForeground(new java.awt.Color(255, 0, 204));
        attack_button_OneTimePad.setLabel("Attack");
        attack_button_OneTimePad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack_button_OneTimePadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(encrypt_button_OneTimePad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Decrypt_button_OneTimePad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attack_button_OneTimePad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encrypt_button_OneTimePad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Decrypt_button_OneTimePad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attack_button_OneTimePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vigenere", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 51, 204))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 51, 204));
        jPanel3.setToolTipText("");

        encrypt_button_Vigenere.setActionCommand("Encrypt");
        encrypt_button_Vigenere.setBackground(new java.awt.Color(0, 102, 102));
        encrypt_button_Vigenere.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        encrypt_button_Vigenere.setForeground(new java.awt.Color(255, 0, 204));
        encrypt_button_Vigenere.setLabel("Encrypt");
        encrypt_button_Vigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encrypt_button_VigenereActionPerformed(evt);
            }
        });

        Decrypt_button_Vigenere.setActionCommand("Decrypt");
        Decrypt_button_Vigenere.setBackground(new java.awt.Color(0, 102, 102));
        Decrypt_button_Vigenere.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        Decrypt_button_Vigenere.setForeground(new java.awt.Color(255, 0, 204));
        Decrypt_button_Vigenere.setLabel("Decrypt");
        Decrypt_button_Vigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decrypt_button_VigenereActionPerformed(evt);
            }
        });

        attack_button_Vigenere.setActionCommand("Attack");
        attack_button_Vigenere.setBackground(new java.awt.Color(0, 102, 102));
        attack_button_Vigenere.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        attack_button_Vigenere.setForeground(new java.awt.Color(255, 0, 204));
        attack_button_Vigenere.setLabel("Attack");
        attack_button_Vigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack_button_VigenereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(encrypt_button_Vigenere, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Decrypt_button_Vigenere, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attack_button_Vigenere, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encrypt_button_Vigenere, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Decrypt_button_Vigenere, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attack_button_Vigenere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 51, 204))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 51, 204));

        encrypt_button_DES.setActionCommand("Encrypt");
        encrypt_button_DES.setBackground(new java.awt.Color(0, 102, 102));
        encrypt_button_DES.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        encrypt_button_DES.setForeground(new java.awt.Color(255, 0, 204));
        encrypt_button_DES.setLabel("Encrypt");
        encrypt_button_DES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encrypt_button_DESActionPerformed(evt);
            }
        });

        Decrypt_button_DES.setActionCommand("Decrypt");
        Decrypt_button_DES.setBackground(new java.awt.Color(0, 102, 102));
        Decrypt_button_DES.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        Decrypt_button_DES.setForeground(new java.awt.Color(255, 0, 204));
        Decrypt_button_DES.setLabel("Decrypt");
        Decrypt_button_DES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decrypt_button_DESActionPerformed(evt);
            }
        });

        attack_button_DES.setActionCommand("Attack");
        attack_button_DES.setBackground(new java.awt.Color(0, 102, 102));
        attack_button_DES.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        attack_button_DES.setForeground(new java.awt.Color(255, 0, 204));
        attack_button_DES.setLabel("Attack");
        attack_button_DES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack_button_DESActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(encrypt_button_DES, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Decrypt_button_DES, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attack_button_DES, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encrypt_button_DES, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Decrypt_button_DES, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attack_button_DES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hill", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 51, 204))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 51, 204));

        encrypt_button_Hill.setActionCommand("Encrypt");
        encrypt_button_Hill.setBackground(new java.awt.Color(0, 102, 102));
        encrypt_button_Hill.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        encrypt_button_Hill.setForeground(new java.awt.Color(255, 0, 204));
        encrypt_button_Hill.setLabel("Encrypt");
        encrypt_button_Hill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encrypt_button_HillActionPerformed(evt);
            }
        });

        Decrypt_button_Hill.setActionCommand("Decrypt");
        Decrypt_button_Hill.setBackground(new java.awt.Color(0, 102, 102));
        Decrypt_button_Hill.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        Decrypt_button_Hill.setForeground(new java.awt.Color(255, 0, 204));
        Decrypt_button_Hill.setLabel("Decrypt");
        Decrypt_button_Hill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decrypt_button_HillActionPerformed(evt);
            }
        });

        attack_button_Hill.setActionCommand("Attack");
        attack_button_Hill.setBackground(new java.awt.Color(0, 102, 102));
        attack_button_Hill.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        attack_button_Hill.setForeground(new java.awt.Color(255, 0, 204));
        attack_button_Hill.setLabel("Attack");
        attack_button_Hill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack_button_HillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(encrypt_button_Hill, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Decrypt_button_Hill, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attack_button_Hill, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encrypt_button_Hill, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Decrypt_button_Hill, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attack_button_Hill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rail Fence", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 51, 204))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(255, 51, 204));

        encrypt_button_RailFence.setActionCommand("Encrypt");
        encrypt_button_RailFence.setBackground(new java.awt.Color(0, 102, 102));
        encrypt_button_RailFence.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        encrypt_button_RailFence.setForeground(new java.awt.Color(255, 0, 204));
        encrypt_button_RailFence.setLabel("Encrypt");
        encrypt_button_RailFence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encrypt_button_RailFenceActionPerformed(evt);
            }
        });

        Decrypt_button_RailFence.setActionCommand("Decrypt");
        Decrypt_button_RailFence.setBackground(new java.awt.Color(0, 102, 102));
        Decrypt_button_RailFence.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        Decrypt_button_RailFence.setForeground(new java.awt.Color(255, 0, 204));
        Decrypt_button_RailFence.setLabel("Decrypt");
        Decrypt_button_RailFence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decrypt_button_RailFenceActionPerformed(evt);
            }
        });

        attack_button_RailFence.setActionCommand("Attack");
        attack_button_RailFence.setBackground(new java.awt.Color(0, 102, 102));
        attack_button_RailFence.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        attack_button_RailFence.setForeground(new java.awt.Color(255, 0, 204));
        attack_button_RailFence.setLabel("Attack");
        attack_button_RailFence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack_button_RailFenceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(encrypt_button_RailFence, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Decrypt_button_RailFence, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attack_button_RailFence, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encrypt_button_RailFence, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Decrypt_button_RailFence, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attack_button_RailFence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RSA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 51, 204))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(255, 51, 204));

        encrypt_button_RSA.setActionCommand("Encrypt");
        encrypt_button_RSA.setBackground(new java.awt.Color(0, 102, 102));
        encrypt_button_RSA.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        encrypt_button_RSA.setForeground(new java.awt.Color(255, 0, 204));
        encrypt_button_RSA.setLabel("Encrypt");
        encrypt_button_RSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encrypt_button_RSAActionPerformed(evt);
            }
        });

        Decrypt_button_RSA.setActionCommand("Decrypt");
        Decrypt_button_RSA.setBackground(new java.awt.Color(0, 102, 102));
        Decrypt_button_RSA.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        Decrypt_button_RSA.setForeground(new java.awt.Color(255, 0, 204));
        Decrypt_button_RSA.setLabel("Decrypt");
        Decrypt_button_RSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decrypt_button_RSAActionPerformed(evt);
            }
        });

        attack_button_RSA.setActionCommand("Attack");
        attack_button_RSA.setBackground(new java.awt.Color(0, 102, 102));
        attack_button_RSA.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        attack_button_RSA.setForeground(new java.awt.Color(255, 0, 204));
        attack_button_RSA.setLabel("Attack");
        attack_button_RSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack_button_RSAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(encrypt_button_RSA, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Decrypt_button_RSA, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attack_button_RSA, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encrypt_button_RSA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Decrypt_button_RSA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attack_button_RSA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 51, 204))); // NOI18N
        jPanel8.setForeground(new java.awt.Color(255, 51, 204));

        encrypt_button_AES.setActionCommand("Encrypt");
        encrypt_button_AES.setBackground(new java.awt.Color(0, 102, 102));
        encrypt_button_AES.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        encrypt_button_AES.setForeground(new java.awt.Color(255, 0, 204));
        encrypt_button_AES.setLabel("Encrypt");
        encrypt_button_AES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encrypt_button_AESActionPerformed(evt);
            }
        });

        Decrypt_button_AES.setActionCommand("Decrypt");
        Decrypt_button_AES.setBackground(new java.awt.Color(0, 102, 102));
        Decrypt_button_AES.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        Decrypt_button_AES.setForeground(new java.awt.Color(255, 0, 204));
        Decrypt_button_AES.setLabel("Decrypt");
        Decrypt_button_AES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decrypt_button_AESActionPerformed(evt);
            }
        });

        attack_button_AES.setActionCommand("Attack");
        attack_button_AES.setBackground(new java.awt.Color(0, 102, 102));
        attack_button_AES.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        attack_button_AES.setForeground(new java.awt.Color(255, 0, 204));
        attack_button_AES.setLabel("Attack");
        attack_button_AES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack_button_AESActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(encrypt_button_AES, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Decrypt_button_AES, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attack_button_AES, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encrypt_button_AES, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Decrypt_button_AES, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attack_button_AES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Row Transpostion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 51, 204))); // NOI18N
        jPanel9.setForeground(new java.awt.Color(255, 51, 204));

        encrypt_button_RowTranspostion.setActionCommand("Encrypt");
        encrypt_button_RowTranspostion.setBackground(new java.awt.Color(0, 102, 102));
        encrypt_button_RowTranspostion.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        encrypt_button_RowTranspostion.setForeground(new java.awt.Color(255, 0, 204));
        encrypt_button_RowTranspostion.setLabel("Encrypt");
        encrypt_button_RowTranspostion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encrypt_button_RowTranspostionActionPerformed(evt);
            }
        });

        Decrypt_button_RowTranspostion.setActionCommand("Decrypt");
        Decrypt_button_RowTranspostion.setBackground(new java.awt.Color(0, 102, 102));
        Decrypt_button_RowTranspostion.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        Decrypt_button_RowTranspostion.setForeground(new java.awt.Color(255, 0, 204));
        Decrypt_button_RowTranspostion.setLabel("Decrypt");
        Decrypt_button_RowTranspostion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decrypt_button_RowTranspostionActionPerformed(evt);
            }
        });

        attack_button_RowTranspostion.setActionCommand("Attack");
        attack_button_RowTranspostion.setBackground(new java.awt.Color(0, 102, 102));
        attack_button_RowTranspostion.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        attack_button_RowTranspostion.setForeground(new java.awt.Color(255, 0, 204));
        attack_button_RowTranspostion.setLabel("Attack");
        attack_button_RowTranspostion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack_button_RowTranspostionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(encrypt_button_RowTranspostion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Decrypt_button_RowTranspostion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attack_button_RowTranspostion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encrypt_button_RowTranspostion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Decrypt_button_RowTranspostion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attack_button_RowTranspostion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }//GEN-END:initComponents
    
    private void browse_file(TextField theField ) {//GEN-FIRST:event_browse_key_fileActionPerformed
            JFileChooser fileChooser = new JFileChooser();// /home/abdelkarim/Desktop/filesForCipher
            fileChooser.setCurrentDirectory(new File("usr.home"));
            int result = fileChooser.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
               File selectedFile = fileChooser.getSelectedFile();
               theField.setText(selectedFile.getPath());
               System.out.println("Selected file: " + selectedFile.getAbsolutePath());
            } 
            
    }//GEN-LAST:event_browse_key_fileActionPerformed
    
    private void Browse_plainTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Browse_plainTextActionPerformed
        browse_file(plain_path);
    }//GEN-LAST:event_Browse_plainTextActionPerformed

    private void Browse_cipherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Browse_cipherActionPerformed
        browse_file(cipher_path);
    }//GEN-LAST:event_Browse_cipherActionPerformed

    private void Browse_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Browse_keyActionPerformed
        browse_file(key_path);
    }//GEN-LAST:event_Browse_keyActionPerformed

    private void Browse_attackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Browse_attackActionPerformed
        browse_file(attack_path);
    }//GEN-LAST:event_Browse_attackActionPerformed
    
    String ReadFile(String path){
        FileInputStream in = null;
        StringBuilder ret = new StringBuilder();
        String line;
        try {
            FileReader fileReader =  new FileReader(path);
            BufferedReader bufferedReader =  new BufferedReader(fileReader);
            while((line = bufferedReader.readLine()) != null) {
               ret.append(line+" ");
            } 
            bufferedReader.close();
        }catch(Exception exp){}
        
        StringBuilder result = new StringBuilder();
        for(int i=0;i<ret.length()-1;i++){
        	result.append(ret.charAt(i));
        }
        return result.toString();
    }
    
    void PrintFile(String path, String Text){
        try{
            FileWriter fileWriter = new FileWriter(path);
            BufferedWriter bufferedWriter =  new BufferedWriter(fileWriter);
            bufferedWriter.write(Text);
            bufferedWriter.close();
        }catch(Exception exp){
            
        }
    }
    
    private void encrypt_button_DESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encrypt_button_DESActionPerformed
        DES_Encryptor enc = new DES_Encryptor( ReadFile(key_path.getText()));
        PrintFile(cipher_path.getText(), enc.encrypt(ReadFile(plain_path.getText())));
        enc.DES_key.display();
        enc.display();
    }//done

    private void Decrypt_button_DESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decrypt_button_DESActionPerformed
        DES_Decryptor dec = new DES_Decryptor( ReadFile(key_path.getText()));
        PrintFile(plain_path.getText(), dec.decryp(ReadFile(cipher_path.getText())) );
        dec.display();
    }//done

    private void attack_button_DESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attack_button_DESActionPerformed
        // humm you are kidding me? 
    }//GEN-LAST:event_attack_button_DESActionPerformed

    private void encrypt_button_AESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encrypt_button_AESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encrypt_button_AESActionPerformed

    private void Decrypt_button_AESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decrypt_button_AESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Decrypt_button_AESActionPerformed

    private void attack_button_AESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attack_button_AESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attack_button_AESActionPerformed

    private void encrypt_button_RSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encrypt_button_RSAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encrypt_button_RSAActionPerformed

    private void Decrypt_button_RSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decrypt_button_RSAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Decrypt_button_RSAActionPerformed

    private void attack_button_RSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attack_button_RSAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attack_button_RSAActionPerformed

    private void encrypt_button_OneTimePadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encrypt_button_OneTimePadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encrypt_button_OneTimePadActionPerformed

    private void Decrypt_button_OneTimePadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decrypt_button_OneTimePadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Decrypt_button_OneTimePadActionPerformed

    private void attack_button_OneTimePadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attack_button_OneTimePadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attack_button_OneTimePadActionPerformed

    private void encrypt_button_HillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encrypt_button_HillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encrypt_button_HillActionPerformed

    private void Decrypt_button_HillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decrypt_button_HillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Decrypt_button_HillActionPerformed

    private void attack_button_HillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attack_button_HillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attack_button_HillActionPerformed

    private void encrypt_button_RailFenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encrypt_button_RailFenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encrypt_button_RailFenceActionPerformed

    private void Decrypt_button_RailFenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decrypt_button_RailFenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Decrypt_button_RailFenceActionPerformed

    private void attack_button_RailFenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attack_button_RailFenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attack_button_RailFenceActionPerformed

    private void encrypt_button_RowTranspostionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encrypt_button_RowTranspostionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encrypt_button_RowTranspostionActionPerformed

    private void Decrypt_button_RowTranspostionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decrypt_button_RowTranspostionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Decrypt_button_RowTranspostionActionPerformed

    private void attack_button_RowTranspostionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attack_button_RowTranspostionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attack_button_RowTranspostionActionPerformed

    private void encrypt_button_VigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encrypt_button_VigenereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encrypt_button_VigenereActionPerformed

    private void Decrypt_button_VigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decrypt_button_VigenereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Decrypt_button_VigenereActionPerformed

    private void attack_button_VigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attack_button_VigenereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attack_button_VigenereActionPerformed

    private void open_plainTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_plainTextActionPerformed
        open_file(plain_path);
    }//GEN-LAST:event_open_plainTextActionPerformed

    private void open_cipherTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_cipherTextActionPerformed
        open_file(cipher_path);
    }//GEN-LAST:event_open_cipherTextActionPerformed

    private void open_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_keyActionPerformed
        open_file(key_path);
    }//GEN-LAST:event_open_keyActionPerformed

    private void open_attackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_attackActionPerformed
        open_file(attack_path);
    }//GEN-LAST:event_open_attackActionPerformed

    private void open_file(TextField field) {//GEN-FIRST:event_open_key_fileActionPerformed
        try {
          File file = new File(field.getText());
          Desktop.getDesktop().open(file);
        }catch(Exception exp){
            System.err.println(exp.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Browse_attack;
    private java.awt.Button Browse_cipher;
    private java.awt.Button Browse_key;
    private java.awt.Button Browse_plainText;
    private java.awt.Button Decrypt_button_AES;
    private java.awt.Button Decrypt_button_DES;
    private java.awt.Button Decrypt_button_Hill;
    private java.awt.Button Decrypt_button_OneTimePad;
    private java.awt.Button Decrypt_button_RSA;
    private java.awt.Button Decrypt_button_RailFence;
    private java.awt.Button Decrypt_button_RowTranspostion;
    private java.awt.Button Decrypt_button_Vigenere;
    private java.awt.Button attack_button_AES;
    private java.awt.Button attack_button_DES;
    private java.awt.Button attack_button_Hill;
    private java.awt.Button attack_button_OneTimePad;
    private java.awt.Button attack_button_RSA;
    private java.awt.Button attack_button_RailFence;
    private java.awt.Button attack_button_RowTranspostion;
    private java.awt.Button attack_button_Vigenere;
    private java.awt.TextField attack_path;
    private java.awt.TextField cipher_path;
    private java.awt.Button encrypt_button_AES;
    private java.awt.Button encrypt_button_DES;
    private java.awt.Button encrypt_button_Hill;
    private java.awt.Button encrypt_button_OneTimePad;
    private java.awt.Button encrypt_button_RSA;
    private java.awt.Button encrypt_button_RailFence;
    private java.awt.Button encrypt_button_RowTranspostion;
    private java.awt.Button encrypt_button_Vigenere;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private java.awt.TextField key_path;
    private java.awt.Button open_attack;
    private java.awt.Button open_cipherText;
    private java.awt.Button open_key;
    private java.awt.Button open_plainText;
    private java.awt.TextField plain_path;
    // End of variables declaration//GEN-END:variables

}
